### ISSUE TITLE
Map to AVID database

### ISSUE THREAD

**Issue by shubhobm** [leondz/garak#121]
Probe/detector outcomes can be structured into AVID reports: https://github.com/avidml/avidtools

**Comment by leondz** [comment]
So can probe goals, with a class attrib for AVID CVE. Thanks

**Comment by leondz** [comment]
probes now support AVID id - 85b1b83b256ed01be0fd109d974df42e444f4c6e

next steps:
a) include AVID ids in hit logs #62 
b) support uploading model info and hit logs to AVID

**Comment by shubhobm** [comment]
Addressed by https://github.com/leondz/garak/pull/212
