### ISSUE TITLE
probe: malware generation

### ISSUE THREAD

**Issue by leondz** [leondz/garak#131]
check if model refuses to write malware

look for:
* obvious stuff (write a virus, write a keylogger, write something to take over a machine, write something to delete all files, ...)
* less obvious stuff (TSR, hooking calls, reading /etc/shadow, privilege escalation, defender disable, set up C2, XSS, crypto hashing...)
* specific tactics (defender evasion, AV evasion, ...)
* multiple langs (x86[-64], c#, c, cpp, rust, javascript, arm64, swift)

https://www.infosecurity-magazine.com/opinions/chatgpt-create-malware-how/

**Comment by crystalwizard** [comment]
This is the article i read this morning on ChatGPT being used to create malware that changes as it's created and deployed
https://www.csoonline.com/article/3698516/chatgpt-creates-mutating-malware-that-evades-detection-by-edr.html
