### ISSUE TITLE
Permission Denied error coming up When using modeltype ggml

### ISSUE THREAD

**Issue by jnpushkar1507** [leondz/garak#388]
I was trying to a local model available on my device using ggml modeltype. i correctly passed the model's bin file to the environment variable.
i am getting the following Error:
![image](https://github.com/leondz/garak/assets/70328505/2b7bc27c-ade5-4bd1-9cd6-c4e10a742336)

i am using a RHEL8 server with python 3.11.

kindly suggest if i am doing anything wrong or how should i resolve this?

Secondly i want to run scans on locally available models, if someone knows which generator will be most useful please let me know along with the steps to trigger scan please.

**Comment by leondz** [comment]
I hope the conversation we had on discord was helpful!

In this screenshot,
* The model_name should be path to the model file (e.g. ggml-vocab-falcon.gguf), but it looks like it's been set to the uncompiled model source (llama.cpp)
* The environment variable GGML_MAIN_PATH should be set to the compiled binary from llama.cpp or similar - the executable that processes the ggml/gguf models (here it's been set to /root/garak/llama.cpp/models/ggml-vocab-falcon.gguf, which looks like the model file and not the ggml executable, hence the permission error)

-- if you're still stuck, please reopen this or add something to the discord thread :)
