### ISSUE TITLE
Error when JSON is provided for rest.py

### ISSUE THREAD

**Issue by rc4ne** [leondz/garak#423]
Hello,
I was trying out this amazing tool on REST APIs. I provided my JSON as attached in screenshots and ran into the error "ValueError: No REST endpoint URI definition found in either constructor param, JSON, or --model_name. Please specify one.". Even though I had specified the URI in JSON. Note that I was working on the default REST generator.
<img width="941" alt="git3" src="https://github.com/leondz/garak/assets/83397936/1ea8a987-6180-4c61-a861-a181d41fa410">
<img width="927" alt="git0" src="https://github.com/leondz/garak/assets/83397936/7856c1b3-328d-4b0c-a083-fb020342800f">

I did a bit of digging and found some changes that made it work for me. I think documentation/information for default REST generator can be improved as well. I will summarize it here: 

1. On line 115, instead of "dir(_config.plugins.generators)" simply (_config.plugins.generators). I tried printing out the contents and figured.
2. On line 128, there is a minor typo. Instead of "setattr(self, field, _config.plugins.generator["rest"][field])" it should be "setattr(self, field, _config.plugins.generators["rest"][field])". (Use generators)
3. Instead of using "rest", "rest.RestGenerator" works everywhere since I was working on default one. Ex- _config.plugins.generators["rest.RestGenerator"]

<img width="661" alt="git1" src="https://github.com/leondz/garak/assets/83397936/3d371d20-4551-4057-9d7f-15b0086ceee7">
<img width="814" alt="git2" src="https://github.com/leondz/garak/assets/83397936/e32f402c-538b-4bc4-88da-3d435a24a5f5">

**Comment by leondz** [comment]
Thanks for this, will take a look

**Comment by leondz** [comment]
Agree with all of these - thanks. In branch at 42848619db9347e9a9243dac525f89afb18b4a81. Do these edits fix your immediate issue?

Agree - should definitely be using the default class explicitly. Will schedule tests & better docs as tasks for this generator.
