### ISSUE TITLE
Read Time out error while using Rest Generators

### ISSUE THREAD

**Issue by jnpushkar1507** [leondz/garak#448]
Hi Team, I was recently trying to run scans on a model using REST generator available in garak. 
However i am encountering a read timed out error. looks like the value is hard coded at 10 seconds, which is very low.
i am pasting the error log stack here. 

  File "/usr/local/lib/python3.11/site-packages/garak/generators/rest.py", line 228, in _call_model
    resp = self.http_function(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='-xyz.com, port=80): Read timed out. (read timeout=10)

please look into this at priority since this issue practically makes rest generators impossible to use.

**Comment by leondz** [comment]
Thanks, looking

**Comment by leondz** [comment]
draft fix here, https://github.com/leondz/garak/commit/5c49baafe5fded4c01a9727d06580fe81d0bdc99

**Comment by ls-omar-nbou** [comment]
@jnpushkar1507 I was able to fix the issue using the parameter `request_timeout ` documented in here https://reference.garak.ai/en/latest/garak.generators.rest.html via a JSON definition into a file and pass the filename to --generator_option_file.
`{
   "rest": {
      "RestGenerator": {
         "name": "Chatbot test",
         "uri": "<URL_PATH>",
         "method": "post",
         "headers": {
            "Authorization": "Bearer <TOKEN>",
            "Content-Type": "application/json"
         },
         "req_template_json_object": {
            "api_provider":"groq",
            "chat_history":[{"role":"user","content":"$INPUT"}]
         },
         "response_json": true,
         "response_json_field": "message",
         **"request_timeout": 180**
      }
   }
}
`
Might be a good way to solve your problem by "playing" with the request_timeout when scanning your REST endpoint(s).

**Comment by archidote** [comment]
> [@jnpushkar1507](https://github.com/jnpushkar1507) I was able to fix the issue using the parameter `request_timeout ` documented in here https://reference.garak.ai/en/latest/garak.generators.rest.html via a JSON definition into a file and pass the filename to --generator_option_file. `{ "rest": { "RestGenerator": { "name": "Chatbot test", "uri": "<URL_PATH>", "method": "post", "headers": { "Authorization": "Bearer <TOKEN>", "Content-Type": "application/json" }, "req_template_json_object": { "api_provider":"groq", "chat_history":[{"role":"user","content":"$INPUT"}] }, "response_json": true, "response_json_field": "message", **"request_timeout": 180** } } } ` Might be a good way to solve your problem by "playing" with the request_timeout when scanning your REST endpoint(s).


I confirm, I had the same problem as @jnpushkar1507 

A big thank you to you @ls-omar-nbou , for the fact that you found this attribute that allows me to no longer encounter the error. In my case I use ollama to manage my LLMs locally, but I wanted to go through the REST API, in order to have something more modular and to be able to query any other LLM with an api. 

To make things clearer, here's the json file in question: 

```json
{
   "rest": {
      "RestGenerator": {
         "name": "example service",
         "uri": "http://localhost:11434/api/generate",
         "method": "post",
         "req_template_json_object": {
            "model": "gemma:2b",
            "prompt": "$INPUT",
            "stream": false
          },
         "response_json": true,
         "response_json_field": "response",
         "request_timeout":180
      }
   }
}
```

**Comment by ls-omar-nbou** [comment]
My pleasure @archidote , good luck with everything.
