### ISSUE TITLE
bug: GGML generator non-zero exit code

### ISSUE THREAD

**Issue by stressfulPanda** [leondz/garak#474]
I'm running `python3 -m garak --model_type ggml --model_name /code/llm_models/llama-bot-chat.Q5_K_M.gguf --probes encoding` and I have set the `GGML_MAIN_PATH=/code/llama.cpp/main` in my `.zshrc` and sourced it. 

When I run the above command I get `subprocess.CalledProcessError: Command '['/code/llama.cpp/main', '-m', '/code/llm_models/llama-bot-chat.Q5_K_M.gguf', '-n', '150', '--repeat-penalty', '1.1', '--presence-penalty', '0.0', '--frequency-penalty', '0.0', '--top-k', '40', '--top-p', '0.95', '--temp', '0.8', '-s', 'None', '-p', "1,h(!0JY@l@V0(-1cRL,2)Ji#2_d9P3G(3\\@Q@sR2E!@'@l?>)ARdK-AMR[L@l-&!3+66)Ai;M$An3T-"]' returned non-zero exit status 1.` 

I'm unsure what I have done wrong, I tested the command on both Linux and Mac, and get the same result both times.

**Comment by leondz** [comment]
thanks for this, will take a look. see also #568.

**Comment by leondz** [comment]
fixed in #581
