### ISSUE TITLE
generator: PRIVATE GPT / FastAPI + OpenAI

### ISSUE THREAD

**Issue by secure1-code** [leondz/garak#532]
I have installed GARAK tool on kali linux. I want to scan "Private GPT" (LLM Model), which is locally installed on my system and running on local host. Is it possible to scan "Private GPT" for security vulnerabilities using GARAK.

Link for Private GPT:  github.com/imartinez/privateGPT?tab=readme-ov-file

I would really appreciate if anyone can guide/help me.
Thanks

**Comment by erickgalinkin** [comment]
This should work via the REST generator -- you just need to specify the calling convention and point it to the location of your FastAPI endpoint.
