### ISSUE TITLE
get CLA Assistant to work nicely with branch protection

### ISSUE THREAD

**Issue by leondz** [leondz/garak#563]
CLA Assistant tries, as-is, to update signatures via `main`. This isn't possible when branch protection is on, giving a bumpy committer experience.

**Comment by leondz** [comment]
see also https://github.com/contributor-assistant/github-action/issues/150

**Comment by leondz** [comment]
`main` now no longer requires a PR before merging

**Comment by leondz** [comment]
@jmartin-tech is this best closed for now as resolved/wontfix?

**Comment by sumanth-lingappa** [comment]
what resolution have you found @leondz ?

**Comment by leondz** [comment]
> what resolution have you found @leondz ?

https://github.com/leondz/garak/issues/563#issuecomment-2074808334

**Comment by sumanth-lingappa** [comment]
I didn't understand the resolution you found. Can you please help me understand?

**Comment by leondz** [comment]
we decided removing main branch protection was the best way forward for us, compared to the alternatives
