### ISSUE TITLE
Hitlogfile write exception

### ISSUE THREAD

**Issue by pi194046** [leondz/garak#599]
i am using the below code to test the function generator of garam , when a hit is generated it writes a hitlog file however i am getting the exception

     93                         _config.transient.hitlogfile.write(
     94                             json.dumps(

ValueError: I/O operation on closed file.
when i run the below code in google colab .  My guess is since session is active it causing this issue and is not opening the hitlogfile once its closed 

```
import openai1

import importlib
importlib.reload(garak)

import garak.generators.function

probe="profanity"
model="openai-custom"
report_prefix="runs/garak-{probe}_{model}"
rr=report_prefix.format(probe=probe,model=model)
print("RRR",rr)

cli_command="--model_type function --model_name openai1#greet1 --probes lmrc.Profanity  --report_prefix {report_prefix} --generations 10"
cli_command=cli_command.format(report_prefix=rr)
print("cli command : ",cli_command)
garak.cli.main(cli_command.split())
```

**Comment by leondz** [comment]
Thanks very much for this. Logfile locking is a little sensitive and we'd love to fix this sort of thing. Are you able to share an example notebook that throws this error?

**Comment by pi194046** [comment]
Please find the google colab notebook which simulates the error https://gist.github.com/pi194046/0a1dcb7ab8bf57625d780d3450d52466

I was able to resolve the error for now by editing the file garak/evaluators/base.py by commenting the like `if not _config.transient.hitlogfile:` and always opening . Below is snippet of edited code 


                        #if not _config.transient.hitlogfile:
                        if not _config.reporting.report_prefix:
                                hitlog_filename = f"{_config.reporting.report_dir}/garak.{_config.transient.run_id}.hitlog.jsonl"
                        else:
                                hitlog_filename = (
                                    _config.reporting.report_prefix + ".hitlog.jsonl"
                                )
                        logging.info("hit log in %s", hitlog_filename)
                        _config.transient.hitlogfile = open(
                                hitlog_filename,
                                "w",
                                buffering=1,
                                encoding="utf-8",
                            )

**Comment by leondz** [comment]
super helpful, thank you for the notebook & proposal!

**Comment by leondz** [comment]
Strong chance this is related to #646 - this is a really valuable report
