### ISSUE TITLE
skip ctrl-c capture if verbose mode is on

### ISSUE THREAD

**Issue by leondz** [leondz/garak#619]
Currently, `cli.py` captures breaks, and terminates gracefully, without printing an exception trace.

This makes it hard to find out what was happening at the time ctrl-c/ctrl-break was pressed.

This PR should change behaviour to 

(a) current, graceful exit if the `verbose` value in `_config` is False;
(b) print the full exception trace if `verbose` is asserted

**Comment by leondz** [comment]
see also #603

**Comment by jmartin-tech** [comment]
@leondz would this provide any useful information to the user?  The current behavior is based on a user interaction with the terminal to exit the process. The stack trace at most will list the current line of code the interpreter is processing. If the progress indicators in output are providing the right level of detail, the user in theory already knows what stage the tool was at when the keyboard interrupt was received?

**Comment by leondz** [comment]
@jmartin-tech 
> If the progress indicators in output are providing the right level of detail, the user in theory already knows what stage the tool was at when the keyboard interrupt was received?

Stack trace and tool output operate at different levels of granularity, intentionally. It's good to be able to access both of these levels, while providing friendly UX as default.

Agree that logging the trace on ctrl-c makes sense - terminal output is ephemeral
