### ISSUE TITLE
avoid duplicates in github testing workflow

### ISSUE THREAD

**Issue by leondz** [leondz/garak#627]
`garak-pytest` will invoke multiple tests based on `push`, `pull_request_target` - sometimes both of these trigger and we get dupe tests (e.g. 2x ubuntu / py 3.10)

tried to use [fkirc/skip-duplicate-actions](https://github.com/marketplace/actions/skip-duplicate-actions) in [`tests.yml`](https://github.com/leondz/garak/blob/main/.github/workflows/tests.yml), this may not be configured correctly

**Comment by jmartin-tech** [comment]
Can you link to an example of this occurring, github actions is pretty good at matching action and commit hash to filter this by default, however there are clear differences in what code tested when a `push` occurs vs a PR is opened.

**Comment by leondz** [comment]
Saw this:
<img width="528" alt="image" src="https://github.com/leondz/garak/assets/121934/c91cb214-1e9e-43f1-abdc-4315588256f6">

on https://github.com/leondz/garak/pull/631

two example dupe jobs:
* https://github.com/leondz/garak/actions/runs/8845440480/job/24289335694?pr=631
* https://github.com/leondz/garak/actions/runs/8845434376/job/24289317160?pr=631

**Comment by leondz** [comment]
addressed in #661
