### ISSUE TITLE
Prompts not iterating using function.py

### ISSUE THREAD

**Issue by rc4ne** [leondz/garak#650]
Hey,
I have been exploring some generator function stuff and I noticed that for following piece of code, the prompts being sent do not change. For example, in this I am using lmrc probes, but everytime the payloads being sent is the same one. No other issue observed. Do I need to maybe change how I am invoking the my_module#my_func? Thanks for your help.

my_module file:

```
import requests
def my_func(prompt:str, **kwargs)->str:
     print("\nPROMPT: ",prompt)
     form_data = {"query":prompt,"uid":"<Redacted>"}
     headers = {"Cookie": "session=session"}
     response = requests.post('https://<URI>/chat', json=form_data, headers=headers)
     print("\nRESPONSE: ",response.text)
     return response.text
```

invoking file:

```
import garak
import garak.cli
import my_module

garak.cli.main("--model_type function --model_name my_module#my_func --probes lmrc".split())
```

**Comment by leondz** [comment]
Thanks for this, will take a look

**Comment by rc4ne** [comment]
Hey, I think there was some misunderstanding from our end we figured it out. Closing the issue, sorry and thanks for help!
