### ISSUE TITLE
Contributing to examples or tutorials

### ISSUE THREAD

**Issue by cyberholics** [leondz/garak#721]
### Question
I am interested in making tutorials or examples on how to use garak, maybe technical articles as well.
How do i make these contributions?

**Comment by leondz** [comment]
This sounds cool! I think you can just go ahead, but we'd love to hear about it in our discord channel. Some examples of things people have done on this front are:

* coding guide - https://wiki.hego.tech/llm-security/garak-a-generative-ai-red-teaming-tool
* usage guide - https://www.youtube.com/watch?v=f713_sFqItY

Let me know if we can support you more on this!
