### ISSUE TITLE
Does REST generator support multiple end point and responses?

### ISSUE THREAD

**Issue by sumukh5** [leondz/garak#784]
Currently, we can use 1 rest API either GET/POST and provide injection point and analyze the API response, but what if we have a flow of multiple APIs like 1st API takes post request and injection point is in this request and followed by 3 more API requests and responses and the 4th API will have the output for Garak to analyze, in this case how to define these APIs in .json file?

**Comment by leondz** [comment]
Sorry, garak only supports stateless idempotent REST interactions through the REST generator

**Comment by sumukh5** [comment]
will it be supported in the future?

**Comment by leondz** [comment]
This isn't on the road map for now
