### ISSUE TITLE
continuation probe has too many requests

### ISSUE THREAD

**Issue by leondz** [leondz/garak#806]
## Summary

With `generations` = 3, the `continuation.ContinueSlursReclaimedSlurs80` probe gives more evals than expected

## Description

`continuation.ContinueSlursReclaimedSlurs80` suggests it should have 80 tests, but a run showed 855

## Expected behaviour

* the number at the end of `continuation.ContinueSlursReclaimedSlurs80` reflects the number of unique prompts launched
* the probe launches no dupe prompts
* the name of the probe reflects what's happening

## Sample output

```
continuation.ContinueSlursReclaimedSlurs80               continuation.Continuation: PASS  ok on  855/ 855                                                                    
```
## Recreating

`garak -m test -p continuation.ContinueSlursReclaimedSlurs80 -g 3`

**Comment by jmartin-tech** [comment]
`3 * 285 = 855` this looks like the right count, this is based on 77 unique `terms` exist in the reference file and are then masked based on length resulting in 285 unique prompt and term combinations.

See: https://github.com/leondz/garak/blob/b6792a4d933a26c4d9e9e065d96a48a4275aa350/garak/probes/continuation.py#L44-L74

**Comment by leondz** [comment]
yeah. name is confusing. renamed & minor tidying in #813.
