### ISSUE TITLE
Can I create the probes and detectors plugins by myself？

### ISSUE THREAD

**Issue by chengsiyangbuaa** [leondz/garak#838]
I greatly appreciate the contributions your team has made to the safety of large models and have some questions I'd like to ask. Our team has developed an application based on a large language model and would like to develop a set of tools for detecting vulnerabilities in large models for internal use. Recently, we came across your team's Garak project and related articles. We hope to build on Garak to do the following: **develop probes, develop detectors, and create custom reports**. Does the Garak framework support these needs?

**Comment by jmartin-tech** [comment]
Yes, the project supports custom plugin development, and we highly encourages upstream contribution if you feel the plugins will have value to others. You can also work in a private clone if you don't want publish or contribute the custom plugins upstream at this time.

Also watch #384 for progress on when the project completes support for adding custom local user `plugins` that do not have to be in the installed package folder enabling first class support for bring your own plugin patterns.
