### ISSUE TITLE
UnboundLocalError: local variable 'opts_cli_config' referenced before assignment

### ISSUE THREAD

**Issue by rgstephens** [leondz/garak#961]
## Steps to reproduce

How'd you do it?

```sh
garak --model_type rasa.RestGenerator --generator_options ./garak/localhost.json
```

## Were you following a specific guide/tutorial or reading documentation?

No

## Expected behavior

Run garak test

## Current behavior

`UnboundLocalError: local variable 'opts_cli_config' referenced before assignment`

### garak version

`v0.9.0.16`

## Additional Information

`opts_cli_config` is [accessed](https://github.com/leondz/garak/blob/71d47aa67ecde3afa784861468fced03d65000a9/garak/cli.py#L384) outside of the block where it is [first defined](https://github.com/leondz/garak/blob/71d47aa67ecde3afa784861468fced03d65000a9/garak/cli.py#L359).

Should be initialized to `None` around [line 354](https://github.com/leondz/garak/blob/71d47aa67ecde3afa784861468fced03d65000a9/garak/cli.py#L354)

**Comment by jmartin-tech** [comment]
Closed by #963
