### ISSUE TITLE
Rest generator aborts on Rasa responses

### ISSUE THREAD

**Issue by rgstephens** [leondz/garak#962]
## Steps to reproduce

`garak --config rasa.yml`

## Were you following a specific guide/tutorial or reading documentation?

No

## Expected behavior

Test to execute

## Current behavior

`TypeError: list indices must be integers or slices, not str`

### garak version

`v0.9.0.16`

## Additional Information

Rasa responds with a list of dictionaries instead of a single dictionary which causes the failure [here](https://github.com/leondz/garak/blob/71d47aa67ecde3afa784861468fced03d65000a9/garak/generators/rest.py#L232).

Changing code as follow resolves the issue:

```py
            if isinstance(response_object, list):
                response = [item[self.response_json_field] for item in response_object]
            else:
                response = [response_object[self.response_json_field]]
```

**Comment by jmartin-tech** [comment]
Closed by #963
